version: 2
updates:
- package-ecosystem: docker
  directory: "/Container/NextcloudCron"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/Container/Nextcloud"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
