version: 2
updates:
- package-ecosystem: "docker" 
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    docker:
      applies-to: version-updates 
      patterns:
        - "*"
- package-ecosystem: "github-actions" 
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    github-actions:
      applies-to: version-updates 
      patterns:
        - "*"
