kind: pipeline
type: kubernetes
name: foo

steps:
- name: Nextcloud  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/nextcloud
    context: Container/Nextcloud/
    dockerfile: Container/Nextcloud/Dockerfile
    auto_tag: true
- name: NextcloudCron  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/nextcloud-cron
    context: Container/NextcloudCron/
    dockerfile: Container/NextcloudCron/Dockerfile
    auto_tag: true
- name: NextcloudElastic 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/nextcloud-elasticsearch
    context: Container/NextcloudCron/
    dockerfile: Container/Elasticsearch/Dockerfile
    auto_tag: true

trigger:
  event:
  - push
  - pull_request
  - tag

---
kind: pipeline
type: kubernetes
name: kube-linter-docker-updates

steps:
- name: update dockerfile
  image: craftingit/ci-tools-docker
  commands:
    - bash .ci/updater.sh
    
- name: push commit
  image: appleboy/drone-git-push
  settings:
    remote_name: originssh
    remote: git@github.com:CraftingITde/NextcloudDocker.git
    ssh_key:
      from_secret: GITHUB_SSH_KEY
    branch: v23
    local_ref: v23
    followtags: true

trigger:
  event:
  - cron
