language: shell
services:
- docker

script:
- docker build -t nextcloud Container/Nextcloud/
- docker build -t nextcloud-cron Container/NextcloudCron/
- docker build -t nextcloud-mariadb Container/MariaDB/
- docker build -t nextcloud-elasticsearch Container/Elasticsearch/

deploy:
  - provider: script
    script: bash docker_push_dev.sh
    on:
      branch: master

  - provider: script
    script: bash docker_push_tag.sh
    on:
      tags: true
