version: '2'

services:
  # Nextcloud Database
  db:
    image: postgres:15.1-alpine
    container_name: nextcloud_db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    networks:
      - nextcloudData
  # Nextcloud Database Admin
  db_admin:
    container_name: nextcloud_db_admin
    image: adminer
    restart: always
    ports:
      - 8086:8080 
    networks:
      - nextcloudData 
  # Nextcloud App
  app:  
    image: craftingit/nextcloud:dev
    container_name: nextcloud_app
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./html:/var/www/html
    restart: always
    networks:
      - nextcloudData
      - nextcloudFullText
      - nextcloudOffice
  # Nextcloud App Cron
  app_cron:  
    image: craftingit/nextcloud-cron:dev
    container_name: nextcloud_app_cron
    environment:
      - CRON=1
      - FULLTEXT=1
      - PREVIEW=1
    links:
      - db
    volumes:
      - ./html:/var/www/html
    restart: always
    networks:
      - nextcloudData
      - nextcloudFullText
      - nextcloudOffice
  #Onlyoffice
  #document-server:
  #  container_name: nextcloud_document-server
  #  image: onlyoffice/documentserver:latest
  #  stdin_open: true
  #  tty: true
  #  restart: always
  #  networks:
  #    - nextcloudOffice
  #  ports:
  #    - '8081:80'
  #    - '8043:443'
  #  volumes:
  #    - ./document_data:/var/www/onlyoffice/Data
  #    - ./document_log:/var/log/onlyoffice

networks:
  nextcloudData:
  nextcloudOffice:
  nextcloudFullText:


      
