version: '2'

services:
  # Nextcloud Database
  db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloudData
  # Nextcloud Database Admin
  db_admin:
    container_name: nextcloud_db_admin
    image: adminer
    restart: always
    ports:
      - 8086:8080 
    networks:
      - nextcloudData 
  # Nextcloud App
  app:  
    image: craftingit/nextcloud:dev
    container_name: nextcloud_app
    ports:
      - 8080:80
    links:
      - db
      - elasticsearch
    volumes:
      - ./html:/var/www/html
    restart: always
    networks:
      - nextcloudData
      - nextcloudFullText
      - nextcloudOffice
  # Nextcloud App Cron
  app_cron:  
    image: craftingit/nextcloud-cron:dev
    container_name: nextcloud_app_cron
    environment:
      - CRON=1
      - FULLTEXT=1
      - PREVIEW=1
    links:
      - db
      - elasticsearch
    volumes:
      - ./html:/var/www/html
    restart: always
    networks:
      - nextcloudData
      - nextcloudFullText
      - nextcloudOffice
  #Onlyoffice
  #document-server:
  #  container_name: nextcloud_document-server
  #  image: onlyoffice/documentserver:latest
  #  stdin_open: true
  #  tty: true
  #  restart: always
  #  networks:
  #    - nextcloudOffice
  #  ports:
  #    - '8081:80'
  #    - '8043:443'
  #  volumes:
  #    - ./document_data:/var/www/onlyoffice/Data
  #    - ./document_log:/var/log/onlyoffice
  # elasticsearch
  elasticsearch:
    image: craftingit/nextcloud-elasticsearch:dev
    container_name: nextcloud_elasticsearch
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - nextcloudFullText


networks:
  nextcloudData:
  nextcloudOffice:
  nextcloudFullText:


      