name: release-container
on:
    push:
      tags:
        - '*'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dockerfile: 
                  - {file: 'Container/Nextcloud/Dockerfile', image: 'craftingit/nextcloud', context: 'Container/Nextcloud'}
                  - {file: 'Container/NextcloudCron/Dockerfile', image: 'craftingit/nextcloud-cron', context: 'Container/NextcloudCron'}
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker meta
              id: meta-bot
              uses: docker/metadata-action@v5
              with:
                images: ${{ matrix.dockerfile.image }}
                tags: |
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}
                    type=semver,pattern={{major}}
                    type=semver,pattern=latest
            
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v6
              with:
                platforms: linux/amd64,linux/arm64
                context: ${{ matrix.dockerfile.context }}
                file: ${{ matrix.dockerfile.file }}
                push: true
                tags: ${{ steps.meta-bot.outputs.tags }}