name: update-container
on:
  schedule:
    - cron: "30 6 * * 1"
  workflow_dispatch:  

jobs:
  update-dockerfile:
    runs-on: ubuntu-latest
    container: 
      image: craftingit/ci-tools-docker:0.0.2
      options: --privileged -v /var/run/docker.sock:/var/run/docker.sock
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_BOT }} 

    - name: Fix permissions
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Update Dockerfile
      run: bash .ci/updater.sh
    
    - name: Push changes and tags
      run: |
        git remote set-url origin https://${{ secrets.PAT_BOT }}@github.com/${{ github.repository }}.git
        git push origin ${{ github.ref }}
        git push origin --tags
