name: update-container
on:
  schedule:
    - cron: "30 6 * * 1"

jobs:
  update-dockerfile:
    runs-on: ubuntu-latest
    container: craftingit/ci-tools-docker:0.0.1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 
      with:
        fetch-depth: 0

    - name: Fix permissions
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Update Dockerfile
      run: bash .ci/updater.sh
    
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.PAT_BOT }}
        branch: ${{ github.ref }}
        tags: true
